### SIDE MENU CONSTANTS ###

# MODES
DELETE = 0
CONNECT = 1
SET_VALS = 2
RENAME = 3
SIMULATE = 4
TRUTH = 5

### DRAWING CANVAS CONSTANTS ###

# GATES
GATES = ["INPUT", "OUTPUT", "NOT", "AND2", "OR2"]

# MOVE/DELETE PARAMETERS
GRAB_RADIUS = 20
CONN_RADIUS = 5